# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: preprocessamento.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'preprocessamento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16preprocessamento.proto\x12\x10preprocessamento\"m\n\tDadoBruto\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04zona\x18\x02 \x01(\t\x12\x0c\n\x04tipo\x18\x03 \x01(\t\x12\r\n\x05valor\x18\x04 \x01(\x01\x12\x0f\n\x07unidade\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t\"\xa9\x01\n\x0e\x44\x61\x64oProcessado\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x0c\n\x04zona\x18\x03 \x01(\t\x12\x0c\n\x04tipo\x18\x04 \x01(\t\x12\x19\n\x11valor_normalizado\x18\x05 \x01(\x01\x12\x1b\n\x13unidade_normalizada\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\t\x12\x0c\n\x04\x65rro\x18\x08 \x01(\t2h\n\x17ServicoPreProcessamento\x12M\n\x0cPreProcessar\x12\x1b.preprocessamento.DadoBruto\x1a .preprocessamento.DadoProcessadoB\x17\xaa\x02\x14GrpcPreProcessamentob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'preprocessamento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024GrpcPreProcessamento'
  _globals['_DADOBRUTO']._serialized_start=44
  _globals['_DADOBRUTO']._serialized_end=153
  _globals['_DADOPROCESSADO']._serialized_start=156
  _globals['_DADOPROCESSADO']._serialized_end=325
  _globals['_SERVICOPREPROCESSAMENTO']._serialized_start=327
  _globals['_SERVICOPREPROCESSAMENTO']._serialized_end=431
# @@protoc_insertion_point(module_scope)
