# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analise.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analise.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ranalise.proto\x12\x07\x61nalise\">\n\rPedidoAnalise\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x0c\n\x04zona\x18\x02 \x01(\t\x12\x11\n\tultimas_n\x18\x03 \x01(\x05\"\xf2\x01\n\x10ResultadoAnalise\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x0c\n\x04tipo\x18\x02 \x01(\t\x12\x0c\n\x04zona\x18\x03 \x01(\t\x12\r\n\x05media\x18\x04 \x01(\x01\x12\x0e\n\x06minimo\x18\x05 \x01(\x01\x12\x0e\n\x06maximo\x18\x06 \x01(\x01\x12\x15\n\rdesvio_padrao\x18\x07 \x01(\x01\x12\x13\n\x0bnivel_risco\x18\x08 \x01(\t\x12\x17\n\x0f\x64\x65scricao_risco\x18\t \x01(\t\x12\x19\n\x11timestamp_analise\x18\n \x01(\t\x12\x14\n\x0cnum_medicoes\x18\x0b \x01(\x05\x12\x0c\n\x04\x65rro\x18\x0c \x01(\t2T\n\x0eServicoAnalise\x12\x42\n\rAnalisarDados\x12\x16.analise.PedidoAnalise\x1a\x19.analise.ResultadoAnaliseB\x0e\xaa\x02\x0bGrpcAnaliseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analise_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\013GrpcAnalise'
  _globals['_PEDIDOANALISE']._serialized_start=26
  _globals['_PEDIDOANALISE']._serialized_end=88
  _globals['_RESULTADOANALISE']._serialized_start=91
  _globals['_RESULTADOANALISE']._serialized_end=333
  _globals['_SERVICOANALISE']._serialized_start=335
  _globals['_SERVICOANALISE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
